# This file was generated by GoReleaser. DO NOT EDIT.
cask "opair" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "ef9685b730abdba842b401051a7d5919cbb9c667147768b7301b0f3557f270bf"
      url "https://gitlab.com/philbooth/opair/-/releases/#{version}/downloads/opair_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "504ce4b31285758d426ea9fd3de02a35240438d754c2344008e98a061d708b79"
      url "https://gitlab.com/philbooth/opair/-/releases/#{version}/downloads/opair_#{version}_darwin_arm64.zip"
    end
  end

  name "opair"
  desc "The coding harness that eschews autonomy."
  homepage "https://opairdev.org"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "opair"

  postflight do
    # Copy the bundled assets into the user config directory, mirroring
    # the resolution used by the binary's Dir()/LoopDir()/prompt.Dir():
    # $XDG_CONFIG_HOME/opair if set, else ~/Library/Application
    # Support/opair on macOS.
    if ENV["XDG_CONFIG_HOME"] && !ENV["XDG_CONFIG_HOME"].empty?
      config_dir = Pathname(ENV["XDG_CONFIG_HOME"])/"opair"
    else
      config_dir = Pathname(Dir.home)/"Library"/"Application Support"/"opair"
    end

    config_dir.mkpath unless config_dir.exist?
    %w[config.anthropic.json config.deepseek.json config.enablers.json config.llamacpp.json config.openai.json config.zai.json].each do |config_file|
      FileUtils.cp staged_path/config_file, config_dir/config_file
    end

    # Assets are deliberately copied unconditionally: Opair is alpha and
    # ships updated prompts/tools/loops/mcp regularly, so upgrades should
    # always surface the canonical assets. Users who fork them should
    # point OPAIR_PROMPTS_DIR / OPAIR_TOOLS_DIR / OPAIR_LOOPS_DIR / OPAIR_MCP_DIR
    # elsewhere.
    %w[loops mcp prompts tools].each do |kind|
      target = config_dir/kind
      target.mkpath unless target.exist?
      Dir.children(staged_path/kind).each do |entry|
        FileUtils.cp_r staged_path/kind/entry, target
      end
    end

    puts
    puts "Opair is free, open-source software, licensed under the GNU AGPL."
    puts
    puts "Source code: https://gitlab.com/philbooth/opair"
    puts "Change log:  https://gitlab.com/philbooth/opair/-/blob/main/HISTORY.md"
    puts "License:     https://www.gnu.org/licenses/agpl-3.0.html"
    puts
    puts "You must configure Opair before using it the first time."
    puts "There are some example config files you can copy to get started."
    puts
    puts "Setup Claude:"
    puts "  cp \"#{config_dir}/config.anthropic.json\" \"#{config_dir}/config.json\""
    puts
    puts "Setup Deepseek:"
    puts "  cp \"#{config_dir}/config.deepseek.json\" \"#{config_dir}/config.json\""
    puts
    puts "Setup OpenAI:"
    puts "  cp \"#{config_dir}/config.openai.json\" \"#{config_dir}/config.json\""
    puts
    puts "Setup GLM:"
    puts "  cp \"#{config_dir}/config.zai.json\" \"#{config_dir}/config.json\""
    puts
    puts "Setup Llama.cpp:"
    puts "  cp \"#{config_dir}/config.llamacpp.json\" \"#{config_dir}/config.json\""
    puts
    puts "Provider authentication is via environment variables: `ANTHROPIC_API_KEY`, `OPENAI_API_KEY`, etc."
    puts "For more information about this or anything else setup-related, see the config doc:"
    puts "https://gitlab.com/philbooth/opair/-/blob/main/docs/config.md"
    puts
  end

  # No zap stanza required

end
