# This file was generated by GoReleaser. DO NOT EDIT.
cask "opair" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "af8052224310a33e594e019f4ecccce41e86e1285605c32546bba3284b497809"
      url "https://gitlab.com/philbooth/opair/-/releases/#{version}/downloads/opair_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "f69ad61ddcadff7932de9eeedd3886704d028ff3fbf45373792450d7264eed52"
      url "https://gitlab.com/philbooth/opair/-/releases/#{version}/downloads/opair_#{version}_darwin_arm64.zip"
    end
  end

  name "opair"
  desc "The coding harness that eschews autonomy."
  homepage "https://opairdev.org"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "opair"

  postflight do
    # Copy the bundled assets into the user config directory, mirroring
    # the resolution used by the binary's Dir()/LoopDir()/prompt.Dir():
    # $XDG_CONFIG_HOME/opair if set, else ~/Library/Application
    # Support/opair on macOS.
    if ENV["XDG_CONFIG_HOME"] && !ENV["XDG_CONFIG_HOME"].empty?
      config_dir = Pathname(ENV["XDG_CONFIG_HOME"])/"opair"
    else
      config_dir = Pathname(Dir.home)/"Library"/"Application Support"/"opair"
    end

    config_dir.mkpath unless config_dir.exist?
    %w[config.anthropic.json config.deepseek.json config.openai.json].each do |config_file|
      FileUtils.cp staged_path/config_file, config_dir/config_file
    end

    # Assets are deliberately copied unconditionally: Opair is alpha and
    # ships updated prompts/tools/loops regularly, so upgrades should
    # always surface the canonical assets. Users who fork them should
    # point OPAIR_PROMPTS_DIR / OPAIR_TOOLS_DIR / OPAIR_LOOPS_DIR
    # elsewhere.
    %w[loops prompts tools].each do |kind|
      target = config_dir/kind
      target.mkpath unless target.exist?
      Dir.children(staged_path/kind).each do |entry|
        FileUtils.cp_r staged_path/kind/entry, target
      end
    end

    ohai "Opair is free, open-source software, licensed under the GNU AGPL."
    puts
    ohai "Source code: https://gitlab.com/philbooth/opair"
    ohai "Change log:  https://gitlab.com/philbooth/opair/-/blob/main/HISTORY.md"
    ohai "License:     https://www.gnu.org/licenses/agpl-3.0.html"
    puts
    ohai "You must configure Opair before using it the first time."
    ohai "There are some example config files you can copy to get started:"
    puts
    puts "For Claude:   cp \"#{config_dir}/config.anthropic.json\" \"#{config_dir}/config.json\""
    puts "For Deepseek: cp \"#{config_dir}/config.deepseek.json\" \"#{config_dir}/config.json\""
    puts "For OpenAI:   cp \"#{config_dir}/config.openai.json\" \"#{config_dir}/config.json\""
    puts
    ohai "For further help configuring Opair, see the readme:"
    ohai "https://gitlab.com/philbooth/opair/-/blob/main/README.md#how-do-i-configure-it"
  end

  # No zap stanza required

end
